### ISSUE TITLE
How to use autocompete in bootstrap modal?

### ISSUE THREAD

**Issue by dkru** [maxivak/bootstrap3_autocomplete_input#16]
Not work in modal window.

**Comment by dkru** [comment]
I have a solution for work autocomplete in modal window. I changed the bootstrap3-autocmplete-input.js
For additional question write to me.

**Comment by maxivak** [comment]
The problem is when you open modal window - javascript code for initializing autocomplete input is not invoked.
One of the solution - run this init script directly after showing modal window or change init script :
```
$(document).ready(function() {
...
}
```
change document.ready to another appropriate event handler.
I will change the scripts to make it easier to use for such inputs which appear dynamically.

**Comment by dkru** [comment]
Thank you for reply.

I transfer code from function on document load to separate function mainfunc from you js file, and add new event listener.
$(document).on('shown.bs.modal', mainfunc)

works on Rails 4.2 and bootstrap 3
